FROM ubuntu:latest

#install Node
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs
RUN node -v
RUN npm -v

#Install AWS CLI
RUN apt-get install -y python3-pip
RUN pip3 install awscli --upgrade
RUN aws --version