# This is a basic workflow to help you get started with Actions

name: Prod Deployment
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:        
      - v0
      - v0.*
      - v1             # Push events to v1 tag
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags
      - v2
      - v2.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build App
      run: npm run ci-build-prod
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
        
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.BKT_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_SECRET }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dist/PortfolioBalancer'      # optional: defaults to entire repository
